accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from django.urls import path
from projects.views import (
    ProjectListView,
    ProjectCreateView,
    ProjectDetailView,
)


urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
]

tasks/urls.py
from django.urls import path
from tasks.views import TaskCreateView, TaskListView, TaskUpdateView


urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path(
        "<int:pk>/complete/", TaskUpdateView.as_view(), name="desription_task"
    ),
]

tracker/urls.py
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.urls import path, include, reverse_lazy

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
]

projects/models.py
from django.db import models
from django.conf import settings

# Create your models here.]

AUTH_USER = settings.AUTH_USER_MODEL


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(
        AUTH_USER,
        related_name="projects",
    )

    def __str__(self):
        return self.name

tasks/models.py
from datetime import date
from django.db import models

from projects.models import AUTH_USER


class Task(models.Model):
    topic = models.CharField(max_length=200)
    date = models.DateField(auto_now=True)
    method = models.CharField(max_length=200, blank=True, null=True)
    link = models.URLField(null=True, blank=True)
    minutes = models.IntegerField(blank=True, null=True)
    understanding = models.BooleanField(default=False)
    description = models.TextField(blank=True, null=True)

    project = models.ForeignKey(
        "projects.Project",
        related_name="tasks",
        on_delete=models.CASCADE,
    )

    assignee = models.ForeignKey(
        AUTH_USER,
        null=True,
        related_name="tasks",
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.topic

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

projects/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from projects.models import Project

# Create your views here.


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"
    context_object_name = "project_list"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members"]

    def get_success_url(self):
        return reverse_lazy("show_project", kwargs={"pk": self.object.pk})


class ProjectDetailView(DetailView):
    model = Project
    template_name = "projects/detail.html"

tasks/views.py
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from tasks.models import Task
from django.urls import reverse_lazy


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = [
        "assignee",
        "topic",
        "method",
        "link",
        "minutes",
        "project",
        "understanding",
    ]

    def get_success_url(self):
        return reverse_lazy("show_my_tasks")


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = "tasks/update.html"
    success_url = reverse_lazy("show_my_tasks")
    fields = ["description"]

projects/templates/base.html
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" href="{% static 'css/app.css' %}">
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->

<html lang="en">

<nav class="nav justify-content-center ">
    <div class="container-fluid">
        {% if user.is_authenticated %}
        <ul class="nav justify-content-center">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'list_projects' %}">Subjects</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'show_my_tasks' %}">Topics</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a> 
            </li>
            
              <li class="nav-item">
                  <a class="nav-link" <a href="{% url 'signup' %}">Signup</a> 
              </li>
          </ul>
          {% endif %}
    </div>
  </nav>
</header>
{% block content %}
{% endblock content %}
</body>

</html>

projects/templates/projects/create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="project-form">
            <h1>Subject</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

projects/templates/projects/detail.html
{% extends 'base.html' %}
{% load markdownify %}

{% block content %}
    <main>
        <div class="project-detail">
            <h1>{{project.name}}</h1>
            {{ project.description|markdownify }}
            <h2>Topics</h2>
            <a href="{% url 'create_task' %}">Create Topic</a>
            {% if project.tasks.all|length > 0 %}
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Topic</th>
                            <th>Date</th>
                            <th>Method</th>
                            <th>Link</th>
                            <th>Time</th>
                            <th>Understand</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in project.tasks.all %}
                            <tr>
                                <td>{{ task.topic }}</td>
                                <td>{{ task.date }}</td>
                                <td>{{ task.method }}</td>
                                {% if task.link is not None %}
                                <td><a href="{{ task.link }}">{{ task.link }}</a></td>
                                {% else %}
                                <td>{{ task.link }}</td>
                                {% endif %}
                                <td>{{ task.minutes }}</td>
                                <td>{{ task.understanding }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>This project has no topics</p>
            {% endif %}
        </div>
    </main>
{% endblock content %}

projects/templates/projects/list.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="project-list">
            <h1>Subjects</h1>
            <a href="{% url 'create_project' %}">add subject</a>
            {% if project_list|length == 0 %}
                <p>You do not have any subjects</p>
            {% else %}
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Number of topics</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for project in project_list %}
                                <tr>
                                    <td>
                                        <a href="{% url 'show_project' project.id %}">{{project.name}}
                                        </td>
                                        <td>{{ project.tasks.all|length }}</td>
                                    </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}

        </main>
{% endblock content %}

projects/templates/tasks/create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="task-form table table-striped">
            <h1>Create a new topic</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

projects/templates/tasks/list.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="my-tasks-list">
            <h1>Topics</h1>
            {% if task_list|length > 0 %}
                        {% for task in task_list %}
                    <div class="accordion" id="accordionExample">
                        <div class="accordion-item">
                          <h2 class="accordion-header" id="headingOne">
                            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                <nav aria-label="breadcrumb">
                                    <ol class="breadcrumb">
                                      <li class="breadcrumb-item"><a href="#">{{ task.project }}</a></li>
                                      <li class="breadcrumb-item active" aria-current="page">{{ task.topic }}</li>
                                    </ol>
                                  </nav>
                            </button>
                          </h2>
                          <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                {% if task.link is not None %}
                                <a href="{{ task.link }}">{{ task.link }}</a>
                                {% else %}
                                {{ task.link }}
                                {% endif %}
                                <a href="{% url 'desription_task' task.id %}">add to notes</a>
                                {% if task.description is not None %}
                                {{ task.description }}
                                {% else %}
                                <div></div>
                                {% endif %}
                            </div>
                          </div>
                        </div>
                           
                        {% endfor %}
                    </tbody>

            {% else %}
                <p>You have no tasks</p>
                </div>
            {% endif %}
        </main>
{% endblock content %}

projects/templates/tasks/update.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="task-form table table-striped">
            <h1>Update Notes</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Update</button>
            </form>
        </div>
    </main>
{% endblock content %}

projects/templates/test.html
{% for task in project.tasks.all %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ task.topic }} on {{ task.date }} by {{ task.method }} for {{ task.minutes }} minutes
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
            {% if task.link is not None %}
            <a href="{{ task.link }}">{{ task.link }}</a>
            {% else %}
            {{ task.link }}
            {% endif %}
        </div>
      </div>
    </div>
  </div>
  {% endfor %}